name: json
version: 2.2.0
date: 2024-01-22
description: |
    Reading and Writing JSON

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/json/
readme: README
packageinfo: https://gap-packages.github.io/json/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/json/releases/download/v2.2.0/json-2.2.0.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
