name: json
version: 2.2.1
date: 2024-04-24
description: |
    Reading and Writing JSON

authors:
    - name: Christopher Jefferson
      url: https://heather.cafe/

maintainers:
    - name: Christopher Jefferson
      url: https://heather.cafe/

GAP: ">= 4.12"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "https://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://gap-packages.github.io/json/
readme: README
packageinfo: https://gap-packages.github.io/json/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/json/releases/download/v2.2.1/json-2.2.1.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
